### PR TITLE
composer: allow Symfony 5

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Could you merge this + tag it?
It's current blocker for my app to got to Symfony 5

**Comment by alterphp** [comment]
tagged as v2.2.0

**Comment by TomasVotruba** [comment]
Thank you!!!

**Comment by alterphp** [comment]
@TomasVotruba  I reverted the merge to the master (and deleted the tag). That did not work due to the top limit of EasyAdmin.

Instead I created this branch to work on unlocking EasyAdmin version : dev/ea-2.2-and-upper. You can try it and see if the feature you are using is still working !

**Comment by TomasVotruba** [comment]
Thank you!

**Pull request merged**
