### PR TITLE
Allow EasyAdmin 2.2.0 and upper

### PR DESCRIPTION
**Pull request by alterphp**

### CODE REVIEW

**Comment by alterphp** [comment]
@qcho @TomasVotruba @amustil @rodrigobb @andrea-daru @gisostallenberg @cobyl @Plopix @fsoedjede @xfifix @mkebza @Amunak Let's continue the conversation on the PR tread

> It seems to work fine for me. Just needed to change the filters usages for ext_filters when including embedded lists manually in twig

This is the BC break introduced by this PR : manually configured filtered list (embedded lists) must use `ext_filters` instead of `filters` (reserved for EasyAdmin native list filters). I'd like to tag the new version `v2.2.0`, so it breaks semver recommendation that would advise v3.0.0 because of the BC break... But I'd like to keep the matching with EasyAdmin versions...

What do you think ? Does this BC break require a new major version (and break matching with EasyAdmin major versions) ?

**Comment by TomasVotruba** [comment]
> But I'd like to keep the matching with EasyAdmin versions...

Not sure if that is possible, when new versoin depend on EasyAdmin not breaking this package.

I'd be completely fine with version 3

**Comment by alterphp** [comment]
Ok @TomasVotruba, thank you for the fast feedback ! Going this way (tagging a major version), I can remove role configuration for menu entries. They are now natively managed by EasyAdmin.

I work on this and then I'll be able to tag the v3.0.0.

**Comment by TomasVotruba** [comment]
Great move, thanks for working on this

**Comment by fsoedjede** [comment]
Hello @alterphp,
It looks good to me. Creating the tag 3.0.0 was the best choice IMO
Thanks for working on this.
I could not test this currently but when I’ll have more time, I’ll give a try

**Comment by alterphp** [comment]
Hi @fsoedjede  and thank you for your feedback.

I've removed the menu permissions as the implementation of EasyAdmin almost covers the same cases. But from what I understand, permissions for actions are a bit different. Custom actions are not covered by item_permission, it's limited to edit/new/show and delete seems not covered as well.

So I prefer to leave the extension implementation to keep the custom actions being secured.

**Pull request merged**
