### PR TITLE
Use EmbeddedLists for SHOW views

### PR DESCRIPTION
**Pull request by alterphp**

### CODE REVIEW

**Comment by helmuthva** [comment]
@alterphp : any chance to have this merged? would be nice to have embedded lists in show.

**Comment by alterphp** [comment]
I'm trying something else as current implementation does not work.

**Comment by alterphp** [comment]
@helmuthva Better working implementation is ongoing.

**Comment by alterphp** [comment]
@helmuthva @sbeff merged and tagged !

**Pull request merged**
