### PR TITLE
Adds max_results config for embedded_lists

### PR DESCRIPTION
**Pull request by alterphp**
Replaces #142 

Following work of @bnbc.

### CODE REVIEW

**Comment by alterphp** [comment]
@bnbc Can you try this branch and tell if it works ?

**Comment by bnbc** [comment]
There is an error : 

Uncaught PHP Exception Twig\Error\RuntimeError: "Variable "masterRequestUri" does not exist." at /var/www/html/mycontract.wilson.local/vendor/alterphp/easyadmin-extension-bundle/src/Resources/views/default/embedded_list.html.twig line 7

**Comment by alterphp** [comment]
@bnbc Are you sure to be on the branch https://github.com/alterphp/EasyAdminExtensionBundle/tree/feature/embedded-list-max-results ? This error happened in an old state that has already been fixed, if I'm not wrong.

**Comment by bnbc** [comment]
My bad it's ok !

**Comment by alterphp** [comment]
Thanks to @bnbc, this PR adds the `max_results` configuration for embedded_lists

**Comment by alterphp** [comment]
@bnbc I've tagged a new version so you can remove the specific branch from your composer.json file and update dependency.

**Comment by bnbc** [comment]
Nice it works good ! Thks.

**Pull request merged**
