### PR TITLE
Fixed if use equal entity on two custom config

### PR DESCRIPTION
**Pull request by gonzakpo**
Example use EventEmbed:
```yaml
easy_admin:
    entities:
        Event:
            class: App\Entity\Event
            list:
                fields:
                    - { property: id , label: 'Id One' }
        EventEmbed:
            class: App\Entity\Event
            list:
                fields:
                    - { property: id , label: 'Id Two Embed' }
        Promoter:
            class: App\Entity\Promoter
            form:
                fields:
                    - { property: events, type: embedded_list, type_options: { entity: EventEmbed } }
```

### CODE REVIEW

**Comment by soyFelixBarros** [comment]
In the show it does not work!

**Comment by gonzakpo** [comment]
@soyFelixBarros 
> In the show it does not work!

Yes working!
Use template_options instead of type_options. Example:
```yaml
easy_admin:
    Promoter:
        class: App\Entity\Promoter
        show:
            fields:
                - { property: events, type: embedded_list, template_options: { entity: EventEmbed } }
```

**Comment by soyFelixBarros** [comment]
thanks!

**Comment by alterphp** [comment]
Sorry but I don't understand the issue it solves, and I won't accept a code
deletion that way.

This code makes sense when you map the same entity many times in easy_admin
config...

Can you describe the issue please ?

Le mer. 22 mai 2019 à 19:19, Gonzalo Alonso <notifications@github.com> a
écrit :

**Comment by gonzakpo** [comment]
EasyAdmin allows several configurations for the same entity.
For example: If different roles are handled, and according to the role, show or hide fields.
All this is lost by having that code.

**Comment by alterphp** [comment]
It's not lost, but the guesser can not guess which easyadmin entity it must
embed. That's why you have to explicitly configure the entity to embed if
the guesser can not...

It works when you add entity in type_options ?

Le mer. 22 mai 2019 à 19:32, Gonzalo Alonso <notifications@github.com> a
écrit :

**Comment by gonzakpo** [comment]
Yes it work.

**Comment by alterphp** [comment]
So, this is the expected behavior.

Le mer. 22 mai 2019 à 20:13, Gonzalo Alonso <notifications@github.com> a
écrit :

**Comment by gonzakpo** [comment]
It is necessary to accept the changes so that everything works.
Limiting 1 configuration to 1 entity does not give any improvement.
It is not flexible.

**Comment by wolverine20** [comment]
I´m agree with the change , if you show many fields in the list view of any entity, and you want to show differents fields or a reduce amount of fields on the embedded_list field type, you can't do it.

**Comment by alterphp** [comment]
Please take the time to explain the exact issue you get. "It does not work" is not an explanation, a sufficient description... What the error message ?

I knwo EasyAdmin allow multiple config for the same entity, I use it and this why this code exists ! So please study the code or explain your issue.

Thank in advance,

**Comment by alterphp** [comment]
There was an error while generating the error message (what the code does), so now it's fixed with 5f6df0e814d50a5ba0aa8e8876fee1f43f147a51.

But setting entity in config was already, and still is the way to achieve what you want.

**Comment by gonzakpo** [comment]
More than 1 entity defined in EasyAdmin configuration matches App\Entity\Event FQCN. Try setting option "entity" (in type_options for NEW/EDIT/FORM view, or template_options for SHOW view) with one of [Event, EventEmbed].
```yaml
easy_admin:
    entities:
        Event:
            class: App\Entity\Event
            list:
                fields:
                    - { property: id , label: 'Id One' }
        EventEmbed:
            class: App\Entity\Event
            list:
                fields:
                    - { property: id , label: 'Id Two Embed' }
        Promoter:
            class: App\Entity\Promoter
            form:
                fields:
                    - { property: events, type: embedded_list, type_options: { entity: EventEmbed } }
```

**Comment by alterphp** [comment]
Can you dump the value of `$matchingEntityConfigs` when the exception is thrown ? And post the exception trace too.

**Comment by gonzakpo** [comment]
```php
EmbeddedListHelper.php on line 89:
array:2 [▼
  "Event" => array:9 [▶]
  "EventEmbed" => array:9 [▶]
]
```
`RuntimeException:
More than 1 entity defined in EasyAdmin configuration matches App\Entity\Event FQCN. Try setting option "entity" (in type_options for NEW/EDIT/FORM view, or template_options for SHOW view) with one of [Event, EventEmbed].

  at vendor/alterphp/easyadmin-extension-bundle/src/Helper/EmbeddedListHelper.php:89
  at AlterPHP\EasyAdminExtensionBundle\Helper\EmbeddedListHelper->guessEntityEntry('App\\Entity\\Event')
     (vendor/alterphp/easyadmin-extension-bundle/src/Configuration/ShowViewConfigPass.php:96)
  at AlterPHP\EasyAdminExtensionBundle\Configuration\ShowViewConfigPass->processTemplateOptions('embedded_list', array('css_class' => '', 'format' => null, 'help' => null, 'label' => 'Event', 'type' => 'embedded_list', 'fieldType' => 'entity', 'dataType' => 'embedded_list', 'virtual' => false, 'sortable' => false, 'template' => '@EasyAdmin/default/label_undefined.html.twig', 'type_options' => array('em' => 'default', 'class' => 'App\\Entity\\Event', 'multiple' => true, 'required' => false), 'form_group' => null, 'fieldName' => 'event', 'mappedBy' => 'id', 'targetEntity' => 'App\\Entity\\Event', 'cascade' => array(), 'orphanRemoval' => false, 'fetch' => 2, 'inversedBy' => null, 'isOwningSide' => false, 'sourceEntity' => 'App\\Entity\\Establishment', 'isCascadeRemove' => false, 'isCascadePersist' => false, 'isCascadeRefresh' => false, 'isCascadeMerge' => false, 'isCascadeDetach' => false, 'associationType' => 4, 'property' => 'events'))
     (vendor/alterphp/easyadmin-extension-bundle/src/Configuration/ShowViewConfigPass.php:61)
  at AlterPHP\EasyAdminExtensionBundle\Configuration\ShowViewConfigPass->processCustomShowTypes(array('r', 'S'))
     (vendor/alterphp/easyadmin-extension-bundle/src/Configuration/ShowViewConfigPass.php:38)
  at AlterPHP\EasyAdminExtensionBundle\Configuration\ShowViewConfigPass->process(array('r', 'S'))
     (vendor/easycorp/easyadmin-bundle/src/Configuration/ConfigManager.php:104)
  at EasyCorp\Bundle\EasyAdminBundle\Configuration\ConfigManager->doProcessConfig(array('r', 'S'))
     (vendor/easycorp/easyadmin-bundle/src/Configuration/ConfigManager.php:117)
  at EasyCorp\Bundle\EasyAdminBundle\Configuration\ConfigManager->loadBackendConfig()
     (vendor/easycorp/easyadmin-bundle/src/Configuration/ConfigManager.php:41)
  at EasyCorp\Bundle\EasyAdminBundle\Configuration\ConfigManager->getBackendConfig()
     (vendor/easycorp/easyadmin-bundle/src/Controller/AdminControllerTrait.php:87)
  at EasyCorp\Bundle\EasyAdminBundle\Controller\EasyAdminController->initialize(object(Request))
     (vendor/easycorp/easyadmin-bundle/src/Controller/AdminControllerTrait.php:60)
  at EasyCorp\Bundle\EasyAdminBundle\Controller\EasyAdminController->indexAction(object(Request))
     (vendor/symfony/http-kernel/HttpKernel.php:150)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:67)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:198)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:25)`

**Comment by alterphp** [comment]
The exception is thrown for a SHOW view (Establishment), not from the form configuration stack...

**Comment by gonzakpo** [comment]
> 
> 
> The exception is thrown for a SHOW view (Establishment), not from the form configuration stack...

The error occurs in any route even / admin

**Comment by alterphp** [comment]
I don't know your project, but the error is not coming from Promoter form configuration, but from **Establishment show** configuration.

**Comment by gonzakpo** [comment]
The error is that it looks for FQCN and finds two config instead of looking for the Key of the config, it is obvious.

**Comment by alterphp** [comment]
Debug your project, you'll see. I have pointed something that I got from the stack trace you posted.

**Comment by gonzakpo** [comment]
You are very right. In all fields you have to set the option entity.

**Comment by alterphp** [comment]
This is only required when there are many EasyAdmin config for the same determined FQCN.

**Pull request closed without merging**
