### PR TITLE
Update easyadmin-extension.js

### PR DESCRIPTION
**Pull request by GeraldGat**

### CODE REVIEW

**Comment by alterphp** [comment]
Please try the following modification (the one that has fixed issue in master branch) : https://github.com/alterphp/EasyAdminExtensionBundle/pull/118/files

**Comment by GeraldGat** [comment]
e.currentTarget don't seems to work.

**Comment by alterphp** [comment]
Can you tell me how to reproduce the bug ? Which part of #148 does it solve ?

**Comment by GeraldGat** [comment]
changing e.target.href to $(this).attr("html") correct the bug opening the same page when clicking on the sort icon

**Comment by GeraldGat** [comment]
To reproduce the bug, just click on the "sort icon" and, If you get the same issue, you'll gate the page replacing your embedded list

**Comment by alterphp** [comment]
OK, thank you for your feedback and the contribution.

**Pull request merged**
